### ISSUE TITLE
Error in antergos-keyring blocks update of packages

### ISSUE THREAD

**Issue by piomiq** [Antergos/antergos-keyring#1]
Hi

Starting yesterday I get following message when I try to update the packages:

cut from octopi

> error: antergos-keyring: signature from "Antergos Build Server (Automated Package Build System) " is unknown trust 
> 
> :: File /var/cache/pacman/pkg/antergos-keyring-20170524-1-any.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
> 
> error: failed to commit transaction (invalid or corrupted package) 
> 

I have enough free space on my disk.
..
regards

**Comment by lots0logs** [comment]
To resolve the issue you need to run this command: `sudo pacman-key --refresh-keys`

**Comment by piomiq** [comment]
Big thanks. Of course after I applied this, all packages have been updated without any problem.
Only I wounder why this command is not included in this package?
Before I met error also when I tried to update from terminal using command: sudo pacman -Syu

**Comment by lots0logs** [comment]
Its not possible in this case. It would have had to have been done before previous key expiration date and we didn't realize that in time :sweat_smile:
